feat: udistrital/sga_documentacion#60 Migración del formulario de espacios académicos y el de agrupación de espacios académicos
udistrital/sga_cliente_espacios_academicos_mf pull request #1
Opened 2024-02-20 15:30 UTC by andresFLZ

2024-03-04 16:20 UTC, NeFaWaltPint commented on src/app/components/agrupacion-espacios-academicos/agrupacion-espacios-academicos.component.html
⚠️  Hay texto quemado en español sin el pipe de translate! 
e.j: `<mat-label>Color agrupación espacios académicos</mat-label>`

2024-03-04 16:21 UTC, NeFaWaltPint commented on src/app/components/form-espacios-academicos/form-espacios-academicos.component.html
⚠️  Falta translate también
ej: `<mat-label>Código abreviación</mat-label>`

2024-03-04 16:27 UTC, NeFaWaltPint commented on src/app/components/form-espacios-academicos/form-espacios-academicos.component.ts
hay alguna lógica que está comentada, e.j: 
```ts
// const idx = this.formDef.campos_p3.findIndex(campo => campo.nombre == 'soporte');
          // if (idx != -1) {
          //   this.desactivarSuprimidos(this.formDef.campos_p3[idx].archivosEnLineaSuprimidos, this.id_espacio_academico);
          // }
```
Pero veo que en las pruebas funciona bien, entiendo que está refactorizado.

2024-03-04 16:27 UTC, NeFaWaltPint commented on src/app/components/list-espacios-academicos/list-espacios-academicos.component.html
traducción: `<th mat-header-cell *matHeaderCellDef> Gestión </th>`

2024-03-04 16:32 UTC, NeFaWaltPint commented on src/assets/i18n/es.json
⚠️  No es necesario poner todas las etiquetas de traducción, únicamente los grupos necesarios. También hay que añadir esos textos que se dejaron en español a este archivo, y al de inglés, que los dos queden exactamente con la misma cantidad de labels.

2024-03-04 16:34 UTC, NeFaWaltPint requested changes
Hay bastantes textos en los *.component.html que no pasan por el pipe de traducción, se requiere agregarlos a assets i18n, tanto en inglés como en español. Y dejar en esos archivos únicamente los grupos de labels necesarios.

2024-03-05 12:37 UTC, andresFLZ commented
Las correcciones ya han sido realizadas

2024-03-07 20:28 UTC, brayaned approved these changes

2024-03-07 20:28 UTC, merged